__title__ = 'jsons'
__version__ = '1.5.1'
__author__ = 'Ramon Hagenaars'
__author_email__ = 'ramon.hagenaars@gmail.com'
__description__ = 'For serializing Python objects to JSON (dicts) and back'
__url__ = 'https://github.com/ramonhagenaars/jsons'
__license__ = 'MIT'
